[package]
name = "circle-manager-meta"
version = "0.1.0"
authors = ["xCircle DAO Contributors"]
edition = "2021"
publish = false

[dependencies.circle-manager]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62.0"

[dev-dependencies]
num-bigint = "0.4"
