[package]
name = "circle-manager-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.circle-manager]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.56.1"

[dev-dependencies]
multiversx-sc-scenario = "0.56.1"
