[package]
name = "circle-of-life-center-meta"
version = "0.1.0"
authors = ["X-CIRCLE-X Team"]
edition = "2021"
publish = false

[dependencies.circle-of-life-center]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62.0"

[dev-dependencies]
num-bigint = "0.4"
